spring.application.name=proyectowebg5

server.port=8080

spring.datasource.url=jdbc:oracle:thin:@llq2026_high
spring.datasource.username=PROYECTO
spring.datasource.password=Fidelitas#2026
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=C:\Oracle\Wallet_IIQ2026

spring.thymeleaf.cache=false